// Generated by LiveScript 1.2.0
var replaceAt, isPattern, removeExtension;
replaceAt = function(index, char, string){
  switch (false) {
  case !(index < 0):
    return string.slice(0, index) + char + string.slice(index + 1);
  default:
    return string.slice(0, index) + char + string.slice(index + 1);
  }
};
isPattern = function(regex, string){
  return regex.test(string);
};
removeExtension = function(it){
  return it.slice(0, it.lastIndexOf("."));
};