// Generated by LiveScript 1.2.0
var infiniteScroll;
infiniteScroll = function(state, e){
  return window.addEventListener("scroll", function(e){
    state.pageY = Math.max(e.pageY || window.pageYOffset, 0);
    state.pageHeight = window.innerHeight;
    return m.redraw();
  });
};