// Generated by LiveScript 1.2.0
var app;
app = {
  view: main,
  controller: Controller
};
m.route.mode = "pathname";
m.route(document, "/", {
  "/": app,
  "/:date.../:post": app,
  "/:page": app
});