// Generated by LiveScript 1.2.0
var mithril, link, menuLinks;
mithril = require('mithril');
link = function(it){
  var result;
  return result = m('a', {
    'class': it['class'] || '',
    href: it.url,
    title: it.title || '',
    config: (it.url || (it.url = [])).indexOf(":") === -1 ? m.route : ""
  }, it.value);
};
menuLinks = function(items){
  return m('ul', (items || []).map(function(it){
    switch (false) {
    case !it:
      return m('li', [link(it)]);
    default:
      return '';
    }
  }));
};
module.exports = {
  link: link,
  menuLinks: menuLinks
};