// Generated by LiveScript 1.2.0
var m, menuLinks, footerMenu;
m = require('mithril');
menuLinks = require('./common').menuLinks;
footerMenu = function(it){
  return m('#footer-menu.pure-menu.pure-menu-open.pure-menu-horizontal.menu', [menuLinks(it)]);
};
module.exports = footerMenu;