// Generated by LiveScript 1.2.0
var mithril, head, menu, header, content, tags, navLinks, archive, footerMenu, footer, main;
mithril = require('mithril');
head = require('./head');
menu = require('./menu');
header = require('./header');
content = require('./content');
tags = require('./tags');
navLinks = require('./nav-links');
archive = require('./archive');
footerMenu = require('./footer-menu');
footer = require('./footer');
main = function(ctrl){
  var config, result;
  config = ctrl.config;
  return result = m('html', [m('head', head(config.head)), m('body', [m('#main', [menu(config.menuItems), header(config.fileType, config.header), content(config.content), tags(config.fileType, config.tags), navLinks(config.data), archive(config.data, config.fileType), footerMenu(config.footerItems), footer(config.footer)])])]);
};
module.exports = main;