// Generated by LiveScript 1.2.0
var mithril, head, menu, header, content, tags, navLinks, footerMenu, footer, post;
mithril = require('mithril');
head = require('./components/head');
menu = require('./components/menu');
header = require('./components/header');
content = require('./components/content');
tags = require('./components/tags');
navLinks = require('./components/nav-links');
footerMenu = require('./components/footer-menu');
footer = require('./components/footer');
post = function(ctrl){
  var config, result;
  config = ctrl.config;
  return result = m('html', [m('head', head(config.head)), m('body', [m('#main', [menu(config.menuItems), header(config.fileType, config.header), content(config.content), tags(config.fileType, config.tags), navLinks(config.data), footerMenu(config.footerItems), footer(config.footer)])])]);
};
module.exports = post;