// Generated by LiveScript 1.2.0
var m, s, tags;
m = require('mithril');
s = require('./../utilities/special');
tags = function(type, tags){
  var attach;
  switch (false) {
  case !s.isPost(m.route()):
    attach = tags.length > 0 ? ' - ' : '';
    return m('p.post-meta.pure-u-1', [m('span', 'Posted ' + s.postDate(m.route()).toDateString() + attach)].concat(tags.map(function(tag){
      return m('span.post-tag', tag);
    })));
  default:
    return '';
  }
};
module.exports = tags;