// Generated by LiveScript 1.2.0
var link, links, head, menu, header, content, postsView, footerMenu, footer, main;
link = function(it){
  var result;
  return result = m('a', {
    'class': it['class'] || '',
    href: it.url,
    title: it.title || '',
    config: it.url.indexOf(":") === -1 ? m.route : ""
  }, it.value);
};
links = function(items){
  return m('ul', (items || []).map(function(it){
    return m('li', [link(it)]);
  }));
};
head = function(head){
  var link, stylesheets;
  link = function(it){
    return m("link", {
      rel: "stylesheet",
      href: it.url
    });
  };
  stylesheets = (head.stylesheets || []).map(link);
  return stylesheets.concat((m('meta', {
    charset: "utf-8"
  }), m('meta', {
    httpEquiv: "X-UA-Compatible",
    content: "IE:edge,chrome:1"
  }), m('meta', {
    name: "viewport",
    content: "width=device-width, initial-scale=1.0"
  }), m('meta', {
    name: "description",
    content: head.description
  }), m("meta", {
    name: "generator",
    content: "maws v0.0.0"
  }), m('title', (head.title ? head.title + ' | ' : '') + "Jon's Blog"), m('link', {
    rel: "shortcut icon",
    href: "./favicon.ico"
  })));
};
menu = function(it){
  return m('.pure-menu.pure-menu-open.pure-menu-horizontal.menu', links(it));
};
header = function(it){
  return m('.header', [
    m('a', {
      href: it.url,
      'class': it['class']
    }, [m('img', {
      src: it.src
    })]), m('h1', it.title), m('h2.subtitle.fancy', m('span', it.subtitle))
  ]);
};
content = function(it){
  return m('article.content', it.article);
};
postsView = function(posts, metadata, type){
  var i;
  switch (type) {
  case 'archive':
    return m('.pure-menu.pure-menu-open.menu', [
      m('.pure-menu-heading', 'Archive'), links((function(){
        var i$, results$ = [];
        for (i$ = metadata.length - 1; i$ >= 0; --i$) {
          i = i$;
          results$.push({
            value: m.trust(metadata[i].title),
            url: posts[i]
          });
        }
        return results$;
      }()))
    ]);
  default:
    return '';
  }
};
footerMenu = function(it){
  return m('#footer-menu.pure-menu.pure-menu-open.pure-menu-horizontal.menu', [links(it)]);
};
footer = function(it){
  return m('footer.footer', [m('p', it.text)]);
};
main = function(ctrl){
  var config, result;
  config = ctrl.config;
  return result = m('html', [m('head', head(config.head)), m('body', [m('#main', [menu(config.menuItems), header(config.header), content(config.content), postsView(config.posts(), config.postMetadata(), config.fileType), footerMenu(config.footerItems), footer(config.footer)])])]);
};