// Generated by LiveScript 1.2.0
var link, links, head, menu, header, content, tagView, postsView, nextPostView, previousPostView, navLinksView, footerMenu, footer, main;
link = function(it){
  var result;
  return result = m('a', {
    'class': it['class'] || '',
    href: it.url,
    title: it.title || '',
    config: (it.url || (it.url = [])).indexOf(":") === -1 ? m.route : ""
  }, it.value);
};
links = function(items){
  return m('ul', (items || []).map(function(it){
    switch (false) {
    case !_.isEmpty(it):
      return '';
    default:
      return m('li', [link(it)]);
    }
  }));
};
head = function(head){
  var link, stylesheets;
  link = function(it){
    return m("link", {
      rel: "stylesheet",
      href: it.url
    });
  };
  stylesheets = (head.stylesheets || []).map(link);
  return stylesheets.concat((m('meta', {
    charset: "utf-8"
  }), m('meta', {
    httpEquiv: "X-UA-Compatible",
    content: "IE:edge,chrome:1"
  }), m('meta', {
    name: "viewport",
    content: "width=device-width, initial-scale=1.0"
  }), m('meta', {
    name: "description",
    content: head.description
  }), m("meta", {
    name: "generator",
    content: "maws v0.0.0"
  }), m('title', (head.title ? head.title + ' | ' : '') + "Jon's Blog"), m('link', {
    rel: "shortcut icon",
    href: "./favicon.ico"
  })));
};
menu = function(it){
  return m('.pure-menu.pure-menu-open.pure-menu-horizontal.menu', links(it));
};
header = function(type, config){
  return m('.header', [m('a', {
    href: config.url,
    'class': config['class']
  }, [m('img', {
    src: config.src
  })])].concat((function(){
    switch (type) {
    case 'page':
    case 'archive':
      return [m('h1', config.title), m('h2', m('span', config.subtitle))];
    default:
      return [];
    }
  }())));
};
content = function(it){
  return m('article.content', it.article);
};
tagView = function(type, tags){
  var attach;
  switch (false) {
  case !isPost():
    attach = tags.length > 0 ? ' - ' : '';
    return m('p.post-meta.pure-u-1', [m('span', 'Posted ' + postDate().toDateString() + attach)].concat(tags.map(function(tag){
      return m('span.post-tag', tag);
    })));
  default:
    return '';
  }
};
postsView = function(posts, metadata, type){
  var i;
  switch (type) {
  case 'archive':
    return m('.pure-menu.pure-menu-open.menu', [
      m('.pure-menu-heading', 'Archive'), links((function(){
        var i$, results$ = [];
        for (i$ = metadata.length - 1; i$ >= 0; --i$) {
          i = i$;
          results$.push({
            value: m.trust(metadata[i].title),
            url: posts[i]
          });
        }
        return results$;
      }()))
    ]);
  default:
    return '';
  }
};
nextPostView = function(posts, metadata, index){
  var linkIndex, post, meta;
  switch (linkIndex = index + 1) {
  case posts.length || metadata.length:
    return '';
  default:
    post = posts[linkIndex];
    meta = metadata[linkIndex];
    return {
      'class': 'navlinks-next',
      url: post,
      title: 'Next Post: ' + meta.title,
      value: m.trust(meta.title + ' &raquo;')
    };
  }
};
previousPostView = function(posts, metadata, index){
  var linkIndex, post, meta;
  switch (linkIndex = index - 1) {
  case -1:
    return '';
  default:
    post = posts[linkIndex];
    meta = metadata[linkIndex];
    return {
      'class': 'navlinks-prev',
      url: post,
      title: 'Previous Post: ' + meta.title,
      value: m.trust('&laquo; ' + meta.title)
    };
  }
};
navLinksView = function(posts, metadata){
  var index, previousPost, nextPost;
  switch (false) {
  case !isPost():
    index = posts.indexOf(m.route());
    previousPost = previousPostView(posts, metadata, index);
    nextPost = nextPostView(posts, metadata, index);
    return m('.pure-menu.pure-menu-open.pure-menu-horizontal.menu', links([previousPost, nextPost]));
  default:
    return '';
  }
};
footerMenu = function(it){
  return m('#footer-menu.pure-menu.pure-menu-open.pure-menu-horizontal.menu', [links(it)]);
};
footer = function(it){
  return m('footer.footer', [m('p', it.text)]);
};
main = function(ctrl){
  var config, result;
  config = ctrl.config;
  return result = m('html', [m('head', head(config.head)), m('body', [m('#main', [menu(config.menuItems), header(config.fileType, config.header), content(config.content), tagView(config.fileType, config.tags), navLinksView(config.posts(), config.postMetadata()), postsView(config.posts(), config.postMetadata(), config.fileType), footerMenu(config.footerItems), footer(config.footer)])])]);
};