// Generated by LiveScript 1.2.0
var t, pagePattern, postPattern, postUglyPattern, postLinkPattern, redirectPattern, withPostUrl, withFriendlyPostUrl, withPostDate, withPageUrl, filterPosts, isPost, postDate;
t = require('./general');
/---Routinglogic---/;
pagePattern = new RegExp("/(\\w+)");
postPattern = new RegExp("/(\\d{4})/(\\d{2})/(\\d{2})/(.+)");
postUglyPattern = new RegExp("(\\d{4})-(\\d{2})-(\\d{2})-(.+)");
postLinkPattern = new RegExp("(\\d{4})-(\\d{2})-(\\d{2})-(.+)");
redirectPattern = '#!/';
withPostUrl = function(match_, year, month, day, postName){
  return "/posts/" + year + "-" + month + "-" + day + "-" + postName + ".html";
};
withFriendlyPostUrl = function(match_, year, month, day, postName){
  var postName_;
  postName_ = removeExtension(postName);
  return "/" + year + "/" + month + "/" + day + "/" + postName_;
};
withPostDate = function(match_, year, month, day){
  return new Date(year, month - 1, day);
};
withPageUrl = function(match_, pageName){
  return "/pages/" + pageName + ".html";
};
filterPosts = function(it){
  return it.filter(function(it){
    return t.isPattern(postLinkPattern, it);
  });
};
isPost = function(it){
  return t.isPattern(postPattern, it);
};
postDate = function(route){
  return new Date(route.replace(postPattern, withPostDate));
};
module.exports = {
  postDate: postDate,
  isPost: isPost
};