// Generated by LiveScript 1.2.0
var m, s, tags;
m = require('mithril');
s = require('./../../utilities/special');
tags = function(type, tags){
  var dash;
  dash = tags.length > 0 ? ' - ' : '';
  return m('p.post-meta.pure-u-1', [m('span', 'Posted ' + s.postDate(m.route()).toDateString() + dash)].concat(tags.map(function(tag){
    return m('span.post-tag', tag);
  })));
};
module.exports = tags;